[versions]
# Libraries versions
ktx = "1.10.1"
runtime-ktx = "2.6.1"
activity-compose = "1.7.2"
material = "1.4.3"
compose-ui = "1.4.3"
junit-junit = "4.13.2"
androidx-junit = "1.1.5"
androidx-espresso = "3.5.1"
# Plugins versions
androidGradlePlugin = "8.0.2"
androidLibraryPlugin = "8.0.2"
jetbrainKotlinPlugin = "1.8.10"
ktlintPlugin = "11.3.1"


[libraries]
androidx-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "ktx" }
androidx-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "runtime-ktx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
androidx-compose-material = { group = "androidx.compose.material", name = "material", version.ref = "material" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose-ui" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "compose-ui" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose-ui" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "compose-ui" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "compose-ui" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-junit" }
androidx-espresso = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidx-espresso" }
junit-junit = { group = "junit", name = "junit", version.ref = "junit-junit" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidLibraryPlugin" }
jetbrain-kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "jetbrainKotlinPlugin" }
jlleitschuh-ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlintPlugin" }
