name: Android Build

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set Up JDK                         // 1
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Change wrapper permissions          // 2
        run: chmod +x ./gradlew

      - name: Setup Gradle                        // 3
        uses: gradle/gradle-build-action@v2

      - name: Run Kotlin Linter                   // 4
        run: ./gradlew ktlintCheck

      - name: Run Tests                           // 5
        run: ./gradlew test

      - name: Build Project                       // 6
        run: ./gradlew build