name: Android Build

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: "Set Up JDK 17"
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu' # Alternative distribution options are available

      - name: "Cache SonarCloud packages"
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: "Change wrapper permissions"
        run: chmod +x ./gradlew

      - name: "Setup Gradle"
        uses: gradle/gradle-build-action@v2

      - name: "Run Ktlint Format"
        run: ./gradlew ktlintFormat

      - name: "Run Detekt"
        run: ./gradlew detekt

      - name: "Build, Test, Generate Coverage Report, and run Sonar"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew sonar --info