name: Android Build

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main

      - name: "Set Up JDK 17"
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu' # Alternative distribution options are available

      - name: "Cache SonarCloud packages"
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: "Change wrapper permissions"
        run: chmod +x ./gradlew

      - name: "Setup Gradle"
        uses: gradle/gradle-build-action@v2

      - name: "Run Ktlint Format"
        run: ./gradlew ktlintFormat

      - name: Build and Test
        run: ./gradlew test

      - name: "Run koverMergedXmlReport"
        run: ./gradlew koverMergedXmlReport

      - name: "Look after report 1"
        run: ls

      - name: "Look after report 2"
        run: ls ./build/reports/kover/merged/xml

      - name: "Look after report 3"
        run: ls build/reports/kover/merged/xml

      - name: "Run sonar"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew sonar